### ISSUE TITLE
coq-geocoq.2.5.0 has no URL

### ISSUE THREAD

**Issue by fblanqui** [coq/opam#3111]

**Comment by silene** [comment]
The package has no source and it does not build anything, so it makes sense that it does not have any url. Does Opam fail to install the package for you?

**Comment by fblanqui** [comment]
Actually, I didn't try. I was computing some statistics about opam packages and found that this one had no url. So I was surprised. I didn't know that it was possible. What is it for?

**Comment by silene** [comment]
There are two cases, either packages whose build instructions fit in the build script (e.g., all the `conf-` packages), or meta-packages whose only role is to install other packages transitively. `coq-geocoq` is the latter.

**Comment by fblanqui** [comment]
I see. Thank you.
